---
title: "L01 Review"
subtitle: "Data Science 3 with R (STAT 301-3)"
author: "Linda Montejo-Bartolon"
pagetitle: "Self Evaluation L01 Linda Montejo-Bartolon"
date: today

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
    toc-location: left
    embed-resources: true
    code-fold: false
    link-external-newwindow: true

execute:
  warning: false

from: markdown+emoji
reference-location: margin
citation-location: margin   
---

::: {.callout-tip icon="false"}
## Github Repo Link


[My Github Repo Link](https://github.com/stat301-3-2026-spring/l01-review-lindamontejo)
:::

## Overview

The goal of this lab is to review machine learning/predictive modeling vocabulary and concepts covered in Data Science 2 with R (STAT 301-2).

## Questions

### Question 1

Provide a brief outline/overview of the steps involved in a supervised machine learning process. Could provide this as a bulleted list. 

::: {.callout-tip icon="false"}
## Solution

Supervised machine learing involves the following process

- Gathering and exploring data analysis: This involves gathering data, coming up with a prediction question, and trying to understand the dataset.
- Feature Engineering / Data processing: Here, the data may be transformed.
- Model Tuning
- Model Assessment 
:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 
3

## Explanation
For this problem, I gave myself a 3 because I missed out on some steps and I wasn't clear when I grouped steps together. I grouped the data acquisition and exploring steps together but I did not mention data cleaning, nor the splitting process. I was too general.

## Updated solution

Supervised machine learing involves the following process: 

- Gathering and exploring data analysis: Data collection, and data preparation and cleaning
- Split the data
- Setup resampling technique such as cross validation
- Feature engineering/recipe building and model specifications
- Model Tuning and comparison
- Select the best model and corresponding hyperparameters
- Fit the best model to the entire training dataset
- Model Assessment 

:::

### Question 2

Explain the difference between supervised and unsupervised learning.

::: {.callout-tip icon="false"}
## Solution

In unsupervised learning there no target or outcome of interest. In this type of learning, there may a structure we want to try to understand. However, supervised learning is task driven and does involve a known target. 

:::
### Self Evaluation

::: {.callout-important icon="false"}

## Score 
4

## Explanation
I wasn't very explicit with why supervised learning might be used. I missed explaining that it can be used to predict the outcome variable well on new, unseen data.

:::

### Question 3 

In general, we can classify a model by its purpose into 1 of the 3 categories below. Provide a brief description of the goals of these model classes.

#### Descriptive Models 

::: {.callout-tip icon="false"}
## Solution

A Descriptive model's main purpose involves describing characteristics of a dataset. Descriptive models help understand patterns and relationships. 
:::


:::

#### Inferential Models

::: {.callout-tip icon="false"}
## Solution

The main purpose of an inferential model is to test a hypothesis regarding relationships in data. This model depends on underlying assumptions.  
:::


#### Predictive Models

::: {.callout-tip icon="false"}
## Solution

A Predictive model is used to make accurate predictions useful for new data.
:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 
4 

## Explanation

The inferential response did not mention that it can be used to produce a decision. 

:::

### Question 4 

We can further describe/classify predictive models by how they were derived or developed as being either mechanistic or empirically driven. 

#### Part (a)

What does it mean to be a mechanistic model?

::: {.callout-tip icon="false"}
## Solution

A mechanistic model is a model which follows a known equation to estimate a set of parameters. These models have limited complexity, but are fast and require little data.

:::

#### Part (b)

What does it mean to be an empirically driven model?

::: {.callout-tip icon="false"}
## Solution

An empirically driven model uses observed data patterns instead of a known equation. This model type requires more data and computation time, but has a better predictive performance. 

:::

#### Part (c)

How does the mechanistic and empirically driven model terminology relate to the parametric and nonparametric model terminology? 

::: {.callout-tip icon="false"}
## Solution

Mechanistic models relate to parametric models because they often have a fixed form and defined parameters. Meanwhile, empirically driven models and nonparametric models are flexible and data-driven; they don't rely on parameters. 
:::

#### Part (d)

In general, is a mechanistic or empirically driven model easier to interpret? Explain.

::: {.callout-tip icon="false"}
## Solution

Mechanistic models can be more easy to interpret because they use known relationships.
:::

#### Part (e)

How does mechanistic and empirically driven model terminology relate to the idea of model flexibility? That is, which would be more or less flexible than the other.

::: {.callout-tip icon="false"}
## Solution

An empirically driven model would be more flexible than a mechanistic model because it adapts to patterns in a dataset. 

:::

#### Part (f)

Describe the bias-variance trade-off when considering the use of a mechanistic or empirically driven model. 

::: {.callout-tip icon="false"}
## Solution

A mechanistic model has a risk of underfitting because it has a higher bias and lower variance. The opposite is true for an empirically driven mode, which risks overfitting by capturing more noise due to lower bias but higher variance. 

:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 
3


## Explanation

For Part A and B I did not include examples. For these responses I also relied on my notes to verfiy the accuracy of my original responses.
## Updated solution

Examples of a mechanistic model include linear and logistic regression. Examples of an empirically model include KNN, random forests, artificial neural networks.

:::

### Question 5 

Explain the difference between a regression and classification machine learning (ML) problems.

::: {.callout-tip icon="false"}
## Solution

In machine learning, regression problems have the final predictions in a quantitative format Meanwhile, for classification problems, the outcome variable is categorical.

:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 
5

## Explanation

The answer correctly identifies the difference between a regression and classification machine learning problems. 

:::

### Question 6 

When splitting the data, why is it useful to stratify by the outcome/target variable? 

::: {.callout-tip icon="false"}
## Solution

Stratifying by the outcome or target variable helps prevent sampling bias by making sure the training and testing data sets have the same distribution of the target variable. 

:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 
4

## Explanation
For this problem, I did not explain what can happen if the outcome variable is not similarly distributed

:::

### Question 7 

Briefly describe how v-fold cross validation with repeats is used to estimate test RMSE. Also provide an explanation of why we use it. 

::: {.callout-tip icon="false"}
## Solution

V-fold cross validation with repeats splits the data into v subsets, trains the model on v-1 folds, and uses the remaining fold as the test set. This creates more variability and provides a more reliable estimate. The model calculates the RMSE on the fold that is used as the test set. It also uses the average of all RMSE values for the final estimated test RMSE.

:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 
2

## Explanation

This response was very broad and missed key reasons on why we use v-fold cross validation with repeats. 
## Updated solution

V-fold cross validation with repeats splits the data into v subsets, trains the model on v-1 folds, and uses the remaining fold as the test set. This is repeated r times. This creates more variability and provides a more reliable estimate. The model calculates the RMSE on the fold that is used as the test set. It also uses the average of all RMSE values for the final estimated test RMSE. The cross-validation procedure allows the model to be trained and evaluated on multiple subsets of the data, and helps to ensure that the estimate of the test RMSE is not overly influenced by the particular split of the data into folds that was used.

:::

### Question 8

When might we use a bootstrap resampling procedure instead of v-fold cross validation to estimate test RMSE?

::: {.callout-tip icon="false"}
## Solution

Bootstrap resampling procedure can be used instead of v-fold cross validation to estimate test RMSE when a dataset is small or when assessing a model's stability or variance.
:::
### Self Evaluation

::: {.callout-important icon="false"}

## Score 
4

## Explanation

I could have been more explicit in my wording. Bootstrap resampling helps reduce the variance of the test RMSE.

:::

### Question 9 

Briefly describe model tuning and why we use it.

::: {.callout-tip icon="false"}
## Solution

Model tunning involves changing the hyper parameters of different models to improve their performance. The goal is to avoid under and over fitting. 

:::
### Self Evaluation
 
::: {.callout-important icon="false"}

## Score 
2

## Explanation
My response was very generic and did not mention all the components of model tuning. Through this reponse, I should've also mentioned model tunning. 
## Updated solution

Model tunning involves changing the hyper parameters of different models to improve their performance. Each new hyperparameter value is a new model. By changing the hyperparameter values we are fitting new models or tuning a specific model type. The goal is to avoid under and over fitting. 


:::

### Question 10 

What are two common performance metrics when dealing with a regression ML problem?

::: {.callout-tip icon="false"}
## Solution

Two common performance metrics when dealing with a regression ML problem **RMSE** and **$r^2$**.

:::

What are two common performance metrics when dealing with a classification ML problem?

::: {.callout-tip icon="false"}
## Solution

Two common performance metrics when dealing with a classification ML problem **ROC AUC** and **accuracy**. 
:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 
5

## Explanation

This questions identifies two performance metrics when dealing with a regression and classification ML problem.


:::

### Question 11

Classify each question/problem below as either prediction or inferential. Explain your reasoning for each.

A company with a subscription based service (for example Netflix, Disney+, New York Times, etc) has data concerning customer interactions with a them, including features like the number of customer service calls, quality of service calls, subscription length, engagement with the service, discounted service, etc. They are interested in two questions:

1. Does a high number of service calls impact a customer's likelihood of churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution

This is an inferential problem because it explores a relationship. Here, the goal is to see whether a high number of service calls can relate to a customer's likelihood of churn in the next month. 
:::

2. How likely is it that a customer will churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution

This is a predictive problem because it attempts to predict the probability of whether a customer will churn in the next month. 
:::


### Self Evaluation

::: {.callout-important icon="false"}

## Score 
4

## Explanation

The response correctly identifies each type of problem, but I did have to reference my notes to make sure.

:::
