---
title: "L01 Review"
subtitle: "Data Science 3 with R (STAT 301-3)"
author: "Linda Montejo-Bartolon"
pagetitle: "L01 Linda Montejo-Bartolon"
date: today

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
    toc-location: left
    embed-resources: true
    code-fold: false
    link-external-newwindow: true

execute:
  warning: false

from: markdown+emoji
reference-location: margin
citation-location: margin   
---

::: {.callout-tip icon="false"}
## Github Repo Link

To link to your github **repo**sitory, appropriately edit the example link below. Meaning replace `https://your-github-repo-url` with your github repo url. Suggest verifying the link works before submitting.

[My Github Repo Link](https://github.com/stat301-3-2026-spring/l01-review-lindamontejo)
:::

## Overview

The goal of this lab is to review machine learning/predictive modeling vocabulary and concepts covered in Data Science 2 with R (STAT 301-2).

## Questions

When completing the following questions ensure your solutions are neatly formatted and clearly indicated. Consider including diagrams/images in some of your solutions, if it helps to make things easier to describe/discuss.

### Question 1

Provide a brief outline/overview of the steps involved in a supervised machine learning process. Could provide this as a bulleted list. 

::: {.callout-tip icon="false"}
## Solution

Supervised machine learing involves the following process

- Gathering and exploring data analysis: This involves gathering data, coming up with a prediction question, and trying to understand the dataset.
- Feature Engineering / Data processing: Here, the data may be transformed.
- Model Tuning
- Model Assessment 
:::

### Question 2

Explain the difference between supervised and unsupervised learning.

::: {.callout-tip icon="false"}
## Solution

In unsupervised learning there no target or outcome of interest. In this type of learning, there may a structure we want to try to understand. However, supervised learning does involve a known target. 

:::

### Question 3 

In general, we can classify a model by its purpose into 1 of the 3 categories below. Provide a brief description of the goals of these model classes.

#### Descriptive Models 

::: {.callout-tip icon="false"}
## Solution

A Descriptive model's main purpose involves describing characteristics of a dataset. Descriptive models help undertand patterns and relationships. 

:::

#### Inferential Models

::: {.callout-tip icon="false"}
## Solution

The main purpose of an inferential model is to test a hypothesis regarding relationships in data.
:::

#### Predictive Models

::: {.callout-tip icon="false"}
## Solution

A Predictive model is used to make predictions useful for new data. Predictive models aim to accurately predict outcomes for new data. 
:::

### Question 4 

We can further describe/classify predictive models by how they were derived or developed as being either mechanistic or empirically driven. 

#### Part (a)

What does it mean to be a mechanistic model?

::: {.callout-tip icon="false"}
## Solution

A mechanistic model is a model which uses an equation to ****finish 

:::

#### Part (b)

What does it mean to be an empirically driven model?

::: {.callout-tip icon="false"}
## Solution

An empirically driven model uses observed data patterns instead of ***finish. 

:::

#### Part (c)

How does the mechanistic and empirically driven model terminology relate to the parametric and nonparametric model terminology? 

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

#### Part (d)

In general, is a mechanistic or empirically driven model easier to interpret? Explain.

::: {.callout-tip icon="false"}
## Solution

Mechanistic models can be more easy to interpret because they use known relationships.
:::

#### Part (e)

How does mechanistic and empirically driven model terminology relate to the idea of model flexibility? That is, which would be more or less flexible than the other.

::: {.callout-tip icon="false"}
## Solution

An empirically driven model would be more flexible than a mechanistic model because it adapts to patterns in a dataset. 

:::

#### Part (f)

Describe the bias-variance trade-off when considering the use of a mechanistic or empirically driven model. 

::: {.callout-tip icon="false"}
## Solution

A mechanistic model can have a higher bias and lower variance. The opposite is true for an empirically driven model

:::

### Question 5 

Explain the difference between a regression and classification machine learning (ML) problems.

::: {.callout-tip icon="false"}
## Solution

In machine learning, regression problems the final predictions are in a quantitative results. Meanwhile, for classification problems, 

:::

### Question 6 

When splitting the data, why is it useful to stratify by the outcome/target variable? 

::: {.callout-tip icon="false"}
## Solution

Stratifying by the outcome or target variable helps prevent sampling bias by making sure the training and testing data sets have the same distribution of the target variable. 

:::

### Question 7 

Briefly describe how v-fold cross validation with repeats is used to estimate test RMSE. Also provide an explanation of why we use it. 

::: {.callout-tip icon="false"}
## Solution

V-fold cross validation with repeats splits the data and trains the model on v-1 folds. This creates more variability and provides a more reliable estimate. 

:::

### Question 8

When might we use a bootstrap resampling procedure instead of v-fold cross validation to estimate test RMSE?

::: {.callout-tip icon="false"}
## Solution

Bootstrap resampling procedure can be used instead of v-fold cross validation to estimate test RMSE when a dataset is small.
:::

### Question 9 

Briefly describe model tuning and why we use it.

::: {.callout-tip icon="false"}
## Solution

Model tunning involves changing the hyperparameters of different models to imporve their performance. The goal is to avoid under and over fitting. 

:::

### Question 10 

What are two common performance metrics when dealing with a regression ML problem?

::: {.callout-tip icon="false"}
## Solution

Two common performance metrics when dealing with a regression ML problem **RMSE** and **r^2**.

:::

What are two common performance metrics when dealing with a classification ML problem?

::: {.callout-tip icon="false"}
## Solution

Two common performance metrics when dealing with a classification ML problem **ROC AUC** and **accuracy**. 
:::

### Question 11

Classify each question/problem below as either prediction or inferential. Explain your reasoning for each.

A company with a subscription based service (for example Netflix, Disney+, New York Times, etc) has data concerning customer interactions with a them, including features like the number of customer service calls, quality of service calls, subscription length, engagement with the service, discounted service, etc. They are interested in two questions:

1. Does a high number of service calls impact a customer's likelihood of churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution

This is an inferential problem because it explore a relationship. Here, the goal is to see whether a high number of service calls can relate to a customer's likelihood of churn in the next month. 
:::

2. How likely is it that a customer will churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution

This is a predictive problem where the goal is predict the probability of whether a customer will churn in the next month. 
:::

